name: Aktualizacja dania dnia

on:
  schedule:
    - cron: "0 7 * * *" # codziennie o 9:00 czasu polskiego (UTC+2)
  workflow_dispatch: # ręczne uruchomienie

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        env:
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          FB_TOKEN: ${{ secrets.FB_TOKEN }}
        run: python bot_danie_dnia.py

      - name: Commit changes
        run: |
          git config user.name "DanieDniaBot"
          git config user.email "bot@users.noreply.github.com"
          git add danie_dnia.html
          git commit -m "Aktualizacja dania dnia"
          git push
