name: Automatyczne pobieranie dania dnia z Facebooka

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  update-danie:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pobierz najnowszy post z Facebooka
        run: |
          PAGE_ID=1450358605057439
          TOKEN=${{ secrets.FB_TOKEN }}

          POST=$(curl -s -G \
            "https://graph.facebook.com/v17.0/$PAGE_ID/posts" \
            -d "access_token=$TOKEN" \
            -d "limit=1" \
            -d "fields=message,id")

          MESSAGE=$(echo $POST | jq -r '.data[0].message')
          POST_ID=$(echo $POST | jq -r '.data[0].id')

          if [ -z "$MESSAGE" ]; then
            echo "Brak nowego posta, pomijam commit."
            exit 0
          fi

          LAST_POST_FILE="last_post_id.txt"
          if [ -f $LAST_POST_FILE ] && [ "$(cat $LAST_POST_FILE)" == "$POST_ID" ]; then
            echo "Post już został przetworzony, pomijam commit."
            exit 0
          fi

          echo "$POST_ID" > $LAST_POST_FILE
          echo "<html><body><h1>Danie dnia</h1><p>$MESSAGE</p></body></html>" > danie_dnia.html

      - name: Commit i push zmian
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add danie_dnia.html last_post_id.txt
          if git diff --cached --quiet; then
            echo "Brak zmian do commita"
          else
            git commit -m "Automatyczna aktualizacja dania dnia $(date +'%Y-%m-%d')"
            git push
          fi
